version: '3.3'

services:
  restapi.postgres:
    container_name: views
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgres-views
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ./.env
    labels:
      com.startupteam.description: "views local postgres"

volumes:
  db_data: {}
